# Generated by Django 5.0.1 on 2024-09-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('senha_certificado', models.CharField(max_length=50)),
                ('local_certificado', models.FileField(upload_to='uploads/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nf', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('status_nfe', models.CharField(max_length=100)),
                ('emissor', models.CharField(max_length=100)),
                ('emissor_cnpj', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=100)),
                ('destinatario_cnpj', models.CharField(max_length=20)),
                ('valor_total', models.CharField(max_length=20)),
                ('xml', models.TextField()),
                ('chaveNfe', models.CharField(max_length=100)),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_NotaFiscal', to='nfe.etiqueta')),
            ],
        ),
    ]
